__author__ = 'xaled'


#TODO: make it oop!


def fillTemplate(template, data):
    output = template
    for k in data:
        output = output.replace("::%s::"%upper(k), data[k])
    return output

def checkConfig(config):
    return True


def createHelper(config):
    checkConfig(config)
    # init vars
    db_name = config['database']
    db_version = config['db_version']
    err_profile = config['error-profile']
    classes = config['classes']
    models_package = "sqlhelper.%s.model"%(db_name)
    models_dir = models_package.replace(".","/")
    helper_package = "sqlhelper.%s.helper"%(db_name)
    helper_dir = helper_package.replace(".","/")


    # create models files
    for c in classes:
        class_name = c['name']
        attributes = c['attributes']
        private_vars = ""
        for a in attributes:
            private_vars += "\n" + fillTemplate(vardeclare_template,{})

#-----------------
#Dictionaries

javatypes = {"string":"String", "int":"long", "bool":"boolean","float":"double","date":"long","blob":"byte[]"}
sqlitetypes = {"string":"TEXT", "int":"INTEGER", "bool":"INTEGER","float":"REAL","date":"INTEGER","blob":"BLOB"}


#-------------------
#TEMPLATES




model_template = """
package ::PACKAGE::;

import java.io.Serializable;

public class  ::CLASSNAME:: implements Serializable{
    /**
     *  ::CLASSNAME:: generated by xaled/sqlhelper for ddatabase ::DBNAME:: version ::DBVERSION::
     *  https://github.com/xaled/sql-helper.git
     */
    private static final long serialVersionUID = 1L;
    //private variables
    ::PRIVATE_VARS::


        // Empty Constructor
        public ::CLASSNAME::(){

        }

        // Full Constuctor
        ::FULLCONSTRUCTOR::

        // Getters and Setters
        ::GETTERS-SETTERS::

	}

"""

getset_template ="""
		// getting ::VARNAME::
		public ::TYPE:: get::VARNAMEUP::(){
			return this.::VARNAMELOW::;

		}
		// setting ::VARNAME::
		public void setID(::TYPE:: ::VARNAMELOW::){
			this.::VARNAMELOW::= ::VARNAMELOW::;
"""

vardeclare_template = """
	private ::TYPE:: ::VARNAMELOW::;
"""

