
package sqlhelper.printfeed.model;

import java.io.Serializable;

public class  FeedItem implements Serializable{
    /**
     *  FeedItem generated by xaled/sqlhelper for database printfeed version 1
     *  https://github.com/xaled/sql-helper.git
     */
    private static final long serialVersionUID = 1L;
    //private variables
    

	private String title;


	private String link;


	private String desc;


	private long srcid;


	private boolean seen;


	private long date;



        // Empty Constructor
        public FeedItem(){

        }

        // Full Constuctor
        
        public FeedItem(String title,String link,String desc,long srcid,boolean seen,long date){

         this.title = title;
         this.link = link;
         this.desc = desc;
         this.srcid = srcid;
         this.seen = seen;
         this.date = date;
        }


        // Getters and Setters
        

		// getting title
		public String getTitle(){
			return this.title;

		}
		// setting title
		public void setTitle(String title){
			this.title= title;
		}


		// getting link
		public String getLink(){
			return this.link;

		}
		// setting link
		public void setLink(String link){
			this.link= link;
		}


		// getting desc
		public String getDesc(){
			return this.desc;

		}
		// setting desc
		public void setDesc(String desc){
			this.desc= desc;
		}


		// getting srcId
		public long getSrcid(){
			return this.srcid;

		}
		// setting srcId
		public void setSrcid(long srcid){
			this.srcid= srcid;
		}


		// getting seen
		public boolean getSeen(){
			return this.seen;

		}
		// setting seen
		public void setSeen(boolean seen){
			this.seen= seen;
		}


		// getting date
		public long getDate(){
			return this.date;

		}
		// setting date
		public void setDate(long date){
			this.date= date;
		}


	}

